apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: fablink-backend-base

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml

commonLabels:
  app: fablink-backend
  component: api
  project: fablink
