apiVersion: v1
kind: ServiceAccount
metadata:
  name: fablink-backend-sa
  annotations:
    # IRSA: IAM Role ARN will be set in environment-specific patches
    # eks.amazonaws.com/role-arn: arn:aws:iam::853963783084:role/fablink-backend-role-dev
automountServiceAccountToken: true
