apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: fablink-dev

# ECR 이미지 설정
images:
  - name: fablink-backend
    newName: 853963783084.dkr.ecr.ap-northeast-2.amazonaws.com/fablink-backend-dev
    newTag: latest

patches:
  - path: configmap-patch.yaml
  - path: service-patch.yaml
  - path: deployment-patch.yaml
  - path: serviceaccount-patch.yaml
  - path: secret-patch.yaml

labels:
  - pairs:
      env: dev
