apiVersion: v1
kind: Secret
metadata:
  name: fablink-secrets
type: Opaque
data:
  # Dev 환경 전용 Django Secret Key
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLWRldi1rZXktZm9yLWRldmVsb3BtZW50LW9ubHktMTIzNDU=

  # Aurora DB 패스워드 (Dev 환경)
  DB_PASSWORD: ZmFibGluazEyMyE=
